name: job
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
        description: "username of player"

      level:
        required: true
        type: string
        description: "level of player"

      class:
        required: true
        type: choice
        description: "choice of player"
        options:
          - jedi
          - sith
          - rebel
          
jobs:
  player_info:
    name: "player info"
    runs-on: ubuntu-latest
    steps:
      - name: "player info"
        run: |
          echo "Le joueur  ${{ inputs.username}} est de niveau  ${{ inputs.level}} et joue un ${{ inputs.choice}}"